name: CD

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    name: Building website
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@master

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.3'
          extended: true
      
      - name: Build website
        run: hugo --minify

      - name: Archive build artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public
  
  deploy:
    name: Deploy website
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: checkout repository
        uses: actions/checkout@master

      - name: Download Build artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: public

      - name: Setup firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_KEY }}